version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
    - "25565:25565"
    - "25575:25575"
    - "4567:4567"
    volumes:
    - "/mnt/minecraft:/data"
    environment:
    - EULA=TRUE
    env_file:
    - minecraft.env
  parrot:
    build:
      context: ./parrot
    ports:
    - "8000:8000"
    env_file:
    - parrot.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 5s
